Traceback (most recent call last):
  File "C:\Users\sayala\AppData\Roaming\Python\Python311\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\ProgramData\Anaconda3\Lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\Lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\Lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\Lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\Anaconda3\Lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\ProgramData\Anaconda3\Lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%%bash
wget https://github.com/LBNL-ETA/Radiance/releases/download/012cb178/Radiance_012cb178_Linux.zip -O radiance.zip
unzip radiance.zip
tar -xvf radiance-5.3.012cb17835-Linux.tar.gz;
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mCalledProcessError[0m                        Traceback (most recent call last)
Cell [1;32mIn[1], line 1[0m
[1;32m----> 1[0m get_ipython()[38;5;241m.[39mrun_cell_magic([38;5;124m'[39m[38;5;124mbash[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mwget https://github.com/LBNL-ETA/Radiance/releases/download/012cb178/Radiance_012cb178_Linux.zip -O radiance.zip[39m[38;5;130;01m\n[39;00m[38;5;124munzip radiance.zip[39m[38;5;130;01m\n[39;00m[38;5;124mtar -xvf radiance-5.3.012cb17835-Linux.tar.gz;[39m[38;5;130;01m\n[39;00m[38;5;124m'[39m)

File [1;32mC:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py:2475[0m, in [0;36mInteractiveShell.run_cell_magic[1;34m(self, magic_name, line, cell)[0m
[0;32m   2473[0m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39mbuiltin_trap:
[0;32m   2474[0m     args [38;5;241m=[39m (magic_arg_s, cell)
[1;32m-> 2475[0m     result [38;5;241m=[39m fn([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m   2477[0m [38;5;66;03m# The code below prevents the output from being displayed[39;00m
[0;32m   2478[0m [38;5;66;03m# when using magics with decodator @output_can_be_silenced[39;00m
[0;32m   2479[0m [38;5;66;03m# when the last Python token in the expression is a ';'.[39;00m
[0;32m   2480[0m [38;5;28;01mif[39;00m [38;5;28mgetattr[39m(fn, magic[38;5;241m.[39mMAGIC_OUTPUT_CAN_BE_SILENCED, [38;5;28;01mFalse[39;00m):

File [1;32mC:\ProgramData\anaconda3\Lib\site-packages\IPython\core\magics\script.py:153[0m, in [0;36mScriptMagics._make_script_magic.<locals>.named_script_magic[1;34m(line, cell)[0m
[0;32m    151[0m [38;5;28;01melse[39;00m:
[0;32m    152[0m     line [38;5;241m=[39m script
[1;32m--> 153[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mshebang(line, cell)

File [1;32mC:\ProgramData\anaconda3\Lib\site-packages\IPython\core\magics\script.py:305[0m, in [0;36mScriptMagics.shebang[1;34m(self, line, cell)[0m
[0;32m    300[0m [38;5;28;01mif[39;00m args[38;5;241m.[39mraise_error [38;5;129;01mand[39;00m p[38;5;241m.[39mreturncode [38;5;241m!=[39m [38;5;241m0[39m:
[0;32m    301[0m     [38;5;66;03m# If we get here and p.returncode is still None, we must have[39;00m
[0;32m    302[0m     [38;5;66;03m# killed it but not yet seen its return code. We don't wait for it,[39;00m
[0;32m    303[0m     [38;5;66;03m# in case it's stuck in uninterruptible sleep. -9 = SIGKILL[39;00m
[0;32m    304[0m     rc [38;5;241m=[39m p[38;5;241m.[39mreturncode [38;5;129;01mor[39;00m [38;5;241m-[39m[38;5;241m9[39m
[1;32m--> 305[0m     [38;5;28;01mraise[39;00m CalledProcessError(rc, cell)

[1;31mCalledProcessError[0m: Command 'b'wget https://github.com/LBNL-ETA/Radiance/releases/download/012cb178/Radiance_012cb178_Linux.zip -O radiance.zip\nunzip radiance.zip\ntar -xvf radiance-5.3.012cb17835-Linux.tar.gz;\n'' returned non-zero exit status 1.
CalledProcessError: Command 'b'wget https://github.com/LBNL-ETA/Radiance/releases/download/012cb178/Radiance_012cb178_Linux.zip -O radiance.zip\nunzip radiance.zip\ntar -xvf radiance-5.3.012cb17835-Linux.tar.gz;\n'' returned non-zero exit status 1.

